wordpress:
  image: wordpress
  links:
    - wordpress_database:mysql
  ports:
    - 8080:80

wordpress_database:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: 1592


phpmyadmin:
  image: corbinu/docker-phpmyadmin
  links:
    - wordpress_database:mysql
  ports:
    - 8181:80
  environment:
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: 1592

